# Generated by Django 2.2.4 on 2020-04-29 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок наовсти')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('picture', models.ImageField(upload_to='images/', verbose_name='Картинка к новости')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
